[package]
name = "jc-photo"
version = "0.1.0"
description = "JC Photo App"
authors = ["julyxx"]
edition = "2021"

# Exclude main.db from Cargo packaging
exclude = ["main.db"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2.2.0"
tauri-plugin-shell = "2"
tauri-plugin-os = "2"
tauri-plugin-fs = "2.2.0"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32.0", features = ["bundled"] }
chrono = "0.4"
kamadak-exif = "0.6.1"
native-dialog = "0.7.0"
dirs = "5.0.1"
walkdir = "2.5.0"
base64 = "0.22.1"
image = "0.25.5"
imagesize = "0.13.0"
# opencv = "0.93.3"
# id3 = "1.14.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
