[package]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
name = "jc-photo"
version = "0.1.0"
description = "July Cat Photo"
homepage = "https://www.jc-photo.com"
authors = ["@liulichuan"]
edition = "2024"
license = "MIT OR Apache-2.0"
exclude = ["main.db"]       # Exclude main.db from Cargo packaging
build = "build.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-window-state = "2.2.1"
tauri-plugin-shell = "2"
tauri-plugin-os = "2"
tauri-plugin-fs = "2.2.0"
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rusqlite = { version = "0.32.0", features = ["bundled", "collation"] }
chrono = "0.4"
kamadak-exif = "0.6.1"
native-dialog = "0.7.0"
dirs = "5.0.1"
walkdir = "2.5.0"
base64 = "0.22.1"
image = "0.25.5"
imagesize = "0.13.0"
tokio = { version = "1.44.1", features = ["full"] }
opener = "0.7.2"
arboard = "3.5.0"
pinyin = "0.10.0"
# opencv = "0.94.4"
# opencv = { version = "0.94.4", features = [
#     "clang-runtime",    # 内置 libclang，不依赖系统 libclang.dylib
#     "imgcodecs",        # 用于图像解码
#     "videoio",          # 用于读取视频
#     "imgproc",          # 用于缩略图处理等
# ] }

# id3 = "1.14.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
